trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build_and_test_stage
  jobs:
  - job: Build_and_test_job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: "Use .NET 6.0 SDK"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
    - task: DotNetCoreCLI@2
      displayName: "Build Huxley 2"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
    - task: DotNetCoreCLI@2
      displayName: "Publish Huxley 2 package"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '**/Huxley2.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Huxley 2 artefact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Huxley 2 to Azure web app service'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(31b2e711-9289-4d65-85b2-5641a7defb04)'
        appType: 'webAppLinux'
        WebAppName: 'huxleytraintracker'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/Huxley2.zip'
        RuntimeStack: 'DOTNETCORE|6.0'
